### PR TITLE
avoid get on $property

### LINKED ISSUE #691: $propName inside interface/type/class is wrongfully transformed
**Describe the bug**
Prop names in interfaces/types/classes starting with `$` are wrongfully converted into `_store_get(..)` calls.

**To Reproduce**
```
<script lang="ts">
  interface A {
    $bla: boolean;
  }

  type B = { $bla: boolean; }

  class C {
    $bla: boolean;
  }
</script>
```

**Expected behavior**
Should not be converted

**System (please complete the following information):**
 - OS: Windows
 - IDE: VSCode
 - Plugin/Package: "Svelte for VSCode", `svelte2tsx`

### PR DESCRIPTION
**Pull request by pushkine**
#691

### CODE REVIEW

File: packages/svelte2tsx/src/svelte2tsx/processInstanceScriptContent.ts [hunk 1]
```diff
@@ -244,7 +244,7 @@ export function processInstanceScriptContent(
         handleStore(node, parent);
     };
 
-    const handleIdentifier = (ident: ts.Identifier, parent: ts.Node) => {
+	const handleIdentifier = (ident: ts.Identifier, parent: ts.Node) => {
```
Comment (dummdidumm) [inline packages/svelte2tsx/src/svelte2tsx/processInstanceScriptContent.ts:247]: Seems like this became a tab. This repo uses spaces for intendation (maybe we should align that with the main repo some day ...)

```suggestion
    const handleIdentifier = (ident: ts.Identifier, parent: ts.Node) => {
```

**Review by dummdidumm — APPROVED** [review]
👍
